#!/usr/bin/env php
<?php

require 'bootstrap.php';

$scriptDir = dirname($_SERVER['SCRIPT_FILENAME']);

$vendorDir = realpath($scriptDir . '/..');
$appRootPath = realpath($vendorDir . '/..');

$autoload = $vendorDir . '/autoload.php';

if(file_exists($autoload)){
    require $autoload;
}

if (!isset($vendorDir)) {
    echo "composer autoloader could not be found.\nYou should run `composer install` in repo root directory.\n";
    exit(1);
}

App::$basePath =  $appRootPath;

$application = new mgine\console\Application([
    'controllerNamespace' => 'mgine\builder\controllers',
    'defaultRoute' => 'help',
    'commandsList' => \mgine\builder\controllers\HelpController::$commandsList,
    'params' => [
        'rootPath' => __DIR__,
        'appRootPath' => $appRootPath,
        'vendorDir' => $vendorDir
    ]
]);

$version = '0.0.1';

print "M-Gine commands ($version)" . PHP_EOL . PHP_EOL;

$application->run();